version: "3.3"

services:
  queue:
    image: rabbitmq:3.9-management-alpine
    container_name: queue
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  db:
    image: redis:3-alpine3.8
    container_name: db
    network_mode: host

  processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: processor
    network_mode: host
    depends_on:
      - db
      - queue
    restart: unless-stopped
    deploy:
      replicas: 2
